version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "0a:f1:27:85:56:44:07:44:50:60:40:8f:1f:73:b5:30" 

      - run:
          name: Github config
          command: |
            git config user.email "matteo.vannucchi11@gmail.com"
            git config user.name "matteo00111"

      - restore_cache:
          keys:
            - node-v1-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependencies
          command: npm ci

      - save_cache:
          key: node-v1-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

      - run: 
          command: | 
            ssh-keyscan -H donpasquale.cs.unibo.it >> ~/.ssh/known_hosts
            scp -r css/ matteo.vannucchi@donpasquale.cs.unibo.it:/home/web/site202120/html/public/frontend/backoffice/css/
            scp -r html/ matteo.vannucchi@donpasquale.cs.unibo.it:/home/web/site202120/html/public/frontend/backoffice/html/
            scp -r js/ matteo.vannucchi@donpasquale.cs.unibo.it:/home/web/site202120/html/public/frontend/backoffice/js/
            scp index.js matteo.vannucchi@donpasquale.cs.unibo.it:/home/web/site202120/html/public/frontend/backoffice/



workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
