version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "5b:7e:cd:32:6c:6e:09:26:2e:17:d5:76:ca:71:6b:2b" 

      - run:
          name: Github config
          command: |
            git config user.email "michele.vir@hotmail.com"
            git config user.name "MicheleVirelli"

      - restore_cache:
          keys:
            - node-v1-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependencies
          command: npm ci

      - save_cache:
          key: node-v1-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

      - run: 
          command: | 
            ssh-keyscan -H donpasquale.cs.unibo.it >> ~/.ssh/known_hosts
            scp -r css/ michele.virelli2@donpasquale.cs.unibo.it:/home/web/site202120/html/public/frontend/backoffice/
            scp -r html/ michele.virelli2@donpasquale.cs.unibo.it:/home/web/site202120/html/public/frontend/backoffice/
            scp -r js/ michele.virelli2@donpasquale.cs.unibo.it:/home/web/site202120/html/public/frontend/backoffice/
            scp nauthHome.html michele.virelli2@donpasquale.cs.unibo.it:/home/web/site202120/html/public/frontend/backoffice/



workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
